hide circle
hide stereotype
hide empty members

ShoppingCenter -- CashRegister:> has
ShoppingCenter -- Customer:> receives
ShoppingCenter -- Cashier:> has

'Cashier -u-|> Person
'Customer -u-|> Person

Cashier -- CashRegister:> serves at

Customer -- Queue:> waits in

Queue -- CashRegister:> delivers a customer to
Customer -- CashRegister:> is served at
